dicussion_board/urls.py
from django.contrib import admin
from django.urls import path,include
from borads import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('borads.url')),
]

borads/models.py
from django.db import models
import psycopg2 as Database
from django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(max_length=255)
    def che(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    board = models.ForeignKey(Board,related_name='topics',on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,related_name='topics', on_delete = models.CASCADE)
    create_dt = models.DateTimeField(auto_now_add=True)

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic,related_name='posts', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)

borads/views.py
from django.shortcuts import render, get_object_or_404
from  django.http import HttpResponse, Http404
from .models import Board
from django.contrib.auth.models import User
from .models import Topic, Post

# Create your views here.

def home(request):
    boards =Board.objects.all()

    return  render(request,'home.html',{'boards':boards})
    # boards_name = []
    # for board in boards:
    #     boards_name.append(board.name)
    # res_ht = '<br>'.join(boards_name)
    # return  HttpResponse(res_ht)

def board_topics(request,board_id):
    # try:
    #     board = Board.objects.get(pk=board_id)
    # except:
    #     raise Http404
    board=get_object_or_404(Board, pk=board_id)
    return render(request, 'topics.html',{'board':board})

def new_topic(request,board_id):
    board=get_object_or_404(Board, pk=board_id)
    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']
        user = User.objects.first()

        topic = Topic.objects.create(
            subject = subject,
            board =board_id,
            created_by =user,
        )
        post = Post.objects.create(
            message=message,
            topic=topic,
            created_by=user
        )
    return render(request,'new_topic.html',{'board':board})






















def about(request):
    return HttpResponse("Hello")

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{%static 'css\bootstrap.min.css'%}">
</head>
<body>

<div class="container">
<ol class="breadcrumb my-4">
{% block breadcrumb %}
    {% endblock %}
</ol>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Boards{%endblock  %}
{% block breadcrumb %}
        <li class="breadcrumb-item active">Boards</li>

    {% endblock %}

  {% block content %}
        <table class="table">
       <thead class="thead-dark">
        <tr>
            <th>Board</th>
            <th>posts</th>
            <th>topic</th>
            <th>last post</th>
        </tr>
       </thead>
        <tbody>
    {% for board in boards %}
    <tr>

        <td> <a href="{% url 'board_topics' board.pk %}"> {{ board.name }}</a>
        <small  class="text-muted d-block">{{ board.description }}</small>

        </td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/new_topic.html
{% extends 'base.html' %}

{% block title %}Create New Topic{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'Home' %}" >Boards</a></li>
    <li class="breadcrumb-item "><a href="{% url 'board_topics' board.pk %}" >{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New Topic</li>
    {% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
        <div class="form-group">
            <label for="id_subject">Subject</label>
            <input type="text" class="form-control" id="id_subject" name="subject">
        </div>
    <div class="form-group">
        <label for="id_message">Message </label>
        <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Post</button>
    </form>
{% endblock %}

templates/topics.html
{% extends 'base.html' %}

{% block title %}{{ board.name }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'Home' %}" >Boards</a></li>
    <li class="breadcrumb-item active">{{ board.name }}</li>
    {% endblock %}

{% block content %}
    {% endblock %}